#ifndef OVERFLOW_PACKET_DISCARD_REGS_H
#define OVERFLOW_PACKET_DISCARD_REGS_H

#include "io.h"

// OVERFLOW PACKET DISCARD ACCESS MACROS

#define OVERFLOW_PACKET_DISCARD_RD_OVERFLOW_PACKET_COUNTER(base)            IORD(base, 0)
#define OVERFLOW_PACKET_DISCARD_CLEAR_OVERFLOW_PACKET_COUNTER(base)         IOWR(base, 0, 0)

#define OVERFLOW_PACKET_DISCARD_OVERFLOW_PACKET_COUNTER_MASK                (0xFFFFFFFF)
#define OVERFLOW_PACKET_DISCARD_OVERFLOW_PACKET_COUNTER_OFST                (0)

#endif /*OVERFLOW_PACKET_DISCARD_REGS_H*/
