// fp_complex_mult.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module fp_complex_mult (
		input  wire [31:0] a,      //      a.a
		input  wire        areset, // areset.reset
		input  wire [31:0] b,      //      b.b
		input  wire [31:0] c,      //      c.c
		input  wire        clk,    //    clk.clk
		input  wire [31:0] d,      //      d.d
		output wire [31:0] q,      //      q.q
		output wire [31:0] r       //      r.r
	);

	fp_complex_mult_altera_fp_functions_181_jqzgwvq fp_functions_0 (
		.clk    (clk),    //    clk.clk
		.areset (areset), // areset.reset
		.a      (a),      //      a.a
		.b      (b),      //      b.b
		.c      (c),      //      c.c
		.d      (d),      //      d.d
		.q      (q),      //      q.q
		.r      (r)       //      r.r
	);

endmodule
