// convert_16bit_fixed_to_floating.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module convert_16bit_fixed_to_floating (
		input  wire [15:0] a,      //      a.a
		input  wire        areset, // areset.reset
		input  wire        clk,    //    clk.clk
		output wire [31:0] q       //      q.q
	);

	convert_16bit_fixed_to_floating_altera_fp_functions_181_jqxcxua fp_functions_0 (
		.clk    (clk),    //    clk.clk
		.areset (areset), // areset.reset
		.a      (a),      //      a.a
		.q      (q)       //      q.q
	);

endmodule
