#ifndef UDP_PAYLOAD_EXTRACTOR_REGS_H
#define UDP_PAYLOAD_EXTRACTOR_REGS_H

#include "io.h"

// UDP PAYLOAD EXTRACTOR ACCESS MACROS

#define UDP_PAYLOAD_EXTRACTOR_RD_PACKET_COUNTER(base)           IORD(base, 0)
#define UDP_PAYLOAD_EXTRACTOR_CLEAR_PACKET_COUNTER(base)        IOWR(base, 0, 0)

#define UDP_PAYLOAD_EXTRACTOR_PACKET_COUNTER_MASK               (0xFFFFFFFF)
#define UDP_PAYLOAD_EXTRACTOR_PACKET_COUNTER_OFST               (0)

#endif /*UDP_PAYLOAD_EXTRACTOR_REGS_H*/
