#ifndef UDP_IMAGE_LINE_PACKET_GENERATOR_REGS_H
#define UDP_IMAGE_LINE_PACKET_GENERATOR_REGS_H

#include "io.h"

// udp_image_line_packet_generator accessor macros

#define UDP_IMAGE_LINE_PACKET_GENERATOR_RD_CSR(base)                  IORD(base, 0)
#define UDP_IMAGE_LINE_PACKET_GENERATOR_WR_CSR(base, data)            IOWR(base, 0, data)

#define UDP_IMAGE_LINE_PACKET_GENERATOR_CSR_GO_BIT_MASK               (0x01)
#define UDP_IMAGE_LINE_PACKET_GENERATOR_CSR_GO_BIT_OFST               (0)


#define UDP_IMAGE_LINE_PACKET_GENERATOR_CSR_RUNNING_BIT_MASK          (0x02)
#define UDP_IMAGE_LINE_PACKET_GENERATOR_CSR_RUNNING_BIT_OFST          (1)

#define UDP_IMAGE_LINE_PACKET_GENERATOR_PRBS_EN_BIT_MASK              (0x04)
#define UDP_IMAGE_LINE_PACKET_GENERATOR_PRBS_EN_BIT_OFST              (2)

#define UDP_IMAGE_LINE_PACKET_GENERATOR_RD_BYTE_COUNT(base)           IORD(base, 1)
#define UDP_IMAGE_LINE_PACKET_GENERATOR_WR_BYTE_COUNT(base, data)     IOWR(base, 1, data)

#define UDP_IMAGE_LINE_PACKET_GENERATOR_BYTE_COUNT_MASK               (0xFFFF)
#define UDP_IMAGE_LINE_PACKET_GENERATOR_BYTE_COUNT_OFST               (0)

#define UDP_IMAGE_LINE_PACKET_GENERATOR_RD_INITIAL_VALUE(base)        IORD(base, 2)
#define UDP_IMAGE_LINE_PACKET_GENERATOR_WR_INITIAL_VALUE(base, data)  IOWR(base, 2, data)

#define UDP_IMAGE_LINE_PACKET_GENERATOR_INITIAL_VALUE_MASK            (0xFFFFFFFF)
#define UDP_IMAGE_LINE_PACKET_GENERATOR_INITIAL_VALUE_OFST            (0)

#define UDP_IMAGE_LINE_PACKET_GENERATOR_RD_PACKET_COUNTER(base)       IORD(base, 3)
#define UDP_IMAGE_LINE_PACKET_GENERATOR_CLEAR_PACKET_COUNTER(base)    IOWR(base, 3, 0)

#define UDP_IMAGE_LINE_PACKET_GENERATOR_PACKET_COUNTER_MASK           (0xFFFFFFFF)
#define UDP_IMAGE_LINE_PACKET_GENERATOR_PACKET_COUNTER_OFST           (0)

#define UDP_IMAGE_LINE_PACKET_GENERATOR_RD_TIMESTAMP31_0(base)       IORD(base, 4)
#define UDP_IMAGE_LINE_PACKET_GENERATOR_CLEAR_TIMESTAMP31_0(base)    IOWR(base, 4, 0)

#define UDP_IMAGE_LINE_PACKET_GENERATOR_TIMESTAMP31_0_MASK           (0xFFFFFFFF)
#define UDP_IMAGE_LINE_PACKET_GENERATOR_TIMESTAMP31_0_OFST           (0)

#define UDP_IMAGE_LINE_PACKET_GENERATOR_RD_TIMESTAMP47_32(base)       IORD(base, 5)
#define UDP_IMAGE_LINE_PACKET_GENERATOR_CLEAR_TIMESTAMP47_32(base)    IOWR(base, 5, 0)

#define UDP_IMAGE_LINE_PACKET_GENERATOR_TIMESTAMP47_32_MASK           (0xFFFF)
#define UDP_IMAGE_LINE_PACKET_GENERATOR_TIMESTAMP47_32_OFST           (0)

#define UDP_IMAGE_LINE_PACKET_GENERATOR_RD_EVENT_ID_AND_LENGTH(base)      	IORD(base, 6)
#define UDP_IMAGE_LINE_PACKET_GENERATOR_WR_EVENT_ID_AND_LENGTH(base, data)  	IOWR(base, 6, data)

#define UDP_IMAGE_LINE_PACKET_GENERATOR_EVENT_ID_AND_LENGTH_MASK          	(0xFFFF)
#define UDP_IMAGE_LINE_PACKET_GENERATOR_EVENT_ID_AND_LENGTH_OFST          	(0)

#define UDP_IMAGE_LINE_PACKET_GENERATOR_RD_EVENT_SOURCE_ADDRESS(base)     	IORD(base, 7)
#define UDP_IMAGE_LINE_PACKET_GENERATOR_WR_EVENT_SOURCE_ADDRESS(base, data)  	IOWR(base, 7, data)

#define UDP_IMAGE_LINE_PACKET_GENERATOR_EVENT_SOURCE_ADDRESS_MASK         	(0xFFFF)
#define UDP_IMAGE_LINE_PACKET_GENERATOR_EVENT_SOURCE_ADDRESS_OFST         	(0)

#endif /*UDP_IMAGE_LINE_PACKET_GENERATOR_REGS_H*/
