// megafunction wizard: %ALTGX%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: alt4gxb
// ============================================================
// File Name: four_lane_seriallite_and_physlite2_xcvr.v
// Megafunction Name(s):
//                      alt4gxb
//
// Simulation Library Files(s):
//                     stratixiv_hssi
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 8.0 SJ Full Version
// ************************************************************
//Copyright (C) 1991-2008 Altera Corporation
//Your use of Altera Corporation's design tools, logic functions
//and other software and tools, and its AMPP partner logic
//functions, and any output files from any of the foregoing
//(including device programming or simulation files), and any
//associated documentation or information are expressly subject
//to the terms and conditions of the Altera Program License
//Subscription Agreement, Altera MegaCore Function License
//Agreement, or other applicable license agreement, including,
//without limitation, that your use is for the sole purpose of
//programming logic devices manufactured by Altera and sold by
//Altera or its authorized distributors.  Please refer to the
//applicable agreement for further details.
// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on

module  four_lane_seriallite_and_phy_slite2_xcvr /* vx2 no_prefix */  (
cal_blk_clk,
gxb_powerdown,
pll_inclk,
reconfig_clk,
reconfig_togxb,
reconfig_fromgxb,
rx_analogreset,
rx_coreclk,
rx_cruclk,
rx_datain,
rx_digitalreset,
rx_enapatternalign,
rx_invpolarity,
rx_seriallpbken,
tx_coreclk,
tx_ctrlenable,
tx_datain,
tx_digitalreset,
pll_locked,
rx_clkout,
rx_ctrldetect,
rx_dataout,
rx_disperr,
rx_errdetect,
rx_freqlocked,
rx_patterndetect,
rx_phase_comp_fifo_error,
rx_pll_locked,
rx_rlv,
rx_syncstatus,
tx_clkout,
tx_dataout,
tx_phase_comp_fifo_error);
input cal_blk_clk;
input[1 - 1:0] gxb_powerdown;
input pll_inclk;
input reconfig_clk;
input[3:0] reconfig_togxb;
output[17 - 1:0] reconfig_fromgxb;
input[4 - 1:0] rx_analogreset;
input[4 - 1:0] rx_coreclk;
input[4 - 1:0] rx_cruclk;
input[4 - 1:0] rx_datain;
input[4 - 1:0] rx_digitalreset;
input[4 - 1:0] rx_enapatternalign;
input[4 - 1:0] rx_invpolarity;
input[4 - 1:0] rx_seriallpbken;
input[4 - 1:0] tx_coreclk;
input[16 - 1:0] tx_ctrlenable;
input[128 - 1:0] tx_datain;
input[4 - 1:0] tx_digitalreset;
output[1 - 1:0] pll_locked;
output[4 - 1:0] rx_clkout;
output[16 - 1:0] rx_ctrldetect;
output[128 - 1:0] rx_dataout;
output[16 - 1:0] rx_disperr;
output[16 - 1:0] rx_errdetect;
output[4 - 1:0] rx_freqlocked;
output[16 - 1:0] rx_patterndetect;
output[4 - 1:0] rx_phase_comp_fifo_error;
output[4 - 1:0] rx_pll_locked;
output[4 - 1:0] rx_rlv;
output[16 - 1:0] rx_syncstatus;
output[4 - 1:0] tx_clkout;
output[4 - 1:0] tx_dataout;
output[4 - 1:0] tx_phase_comp_fifo_error;
wire  cal_blk_clk  ;
wire  [1 - 1:0] gxb_powerdown  ;
wire  pll_inclk  ;
wire  reconfig_clk  ;
wire  [3:0] reconfig_togxb  ;
wire  [17 - 1:0] reconfig_fromgxb  ;
wire  [4 - 1:0] rx_analogreset  ;
wire  [4 - 1:0] rx_coreclk  ;
wire  [4 - 1:0] rx_cruclk  ;
wire  [4 - 1:0] rx_datain  ;
wire  [4 - 1:0] rx_digitalreset  ;
wire  [4 - 1:0] rx_enapatternalign  ;
wire  [4 - 1:0] rx_invpolarity  ;
wire  [4 - 1:0] rx_seriallpbken  ;
wire  [4 - 1:0] tx_coreclk  ;
wire  [16 - 1:0] tx_ctrlenable  ;
wire  [128 - 1:0] tx_datain  ;
wire  [4 - 1:0] tx_digitalreset  ;
wire  [16 - 1:0] rx_ctrldetect  ;
wire  [4 - 1:0] rx_phase_comp_fifo_error  ;
wire  [4 - 1:0] tx_phase_comp_fifo_error  ;
wire  [4 - 1:0] tx_clkout  ;
wire  [1 - 1:0] pll_locked  ;
wire  [4 - 1:0] rx_clkout  ;
wire  [128 - 1:0] rx_dataout  ;
wire  [16 - 1:0] rx_disperr  ;
wire  [16 - 1:0] rx_errdetect  ;
wire  [4 - 1:0] rx_freqlocked  ;
wire  [16 - 1:0] rx_patterndetect  ;
wire  [4 - 1:0] rx_pll_locked  ;
wire  [4 - 1:0] rx_rlv  ;
wire  [16 - 1:0] rx_syncstatus  ;
wire  [4 - 1:0] tx_dataout  ;
wire  [4 - 1:0] sub_wire_zero = 4'h0  ;
 alt4gxb /* vx2 no_prefix*/ alt4gxb_component(.rx_coreclk(rx_coreclk),
.rx_invpolarity(rx_invpolarity), .pll_inclk(pll_inclk),
.gxb_powerdown(gxb_powerdown), .tx_datain(tx_datain),
.rx_revbitorderwa(sub_wire_zero),
.rx_enapatternalign(rx_enapatternalign), .rx_cruclk(rx_cruclk),
.cal_blk_clk(cal_blk_clk), .reconfig_clk(reconfig_clk),
.reconfig_fromgxb(reconfig_fromgxb), .reconfig_togxb(reconfig_togxb),
.rx_seriallpbken(rx_seriallpbken), .rx_datain(rx_datain),
.tx_coreclk(tx_coreclk), .tx_ctrlenable(tx_ctrlenable),
.rx_analogreset(rx_analogreset), .rx_digitalreset(rx_digitalreset),
.tx_digitalreset(tx_digitalreset), .rx_disperr(rx_disperr),
.rx_rlv(rx_rlv), .rx_patterndetect(rx_patterndetect),
.rx_ctrldetect(rx_ctrldetect), .rx_errdetect(rx_errdetect),
.rx_pll_locked(rx_pll_locked), .rx_freqlocked(rx_freqlocked),
.rx_clkout(rx_clkout),
.tx_phase_comp_fifo_error(tx_phase_comp_fifo_error),
.tx_dataout(tx_dataout),
.rx_phase_comp_fifo_error(rx_phase_comp_fifo_error),
.rx_syncstatus(rx_syncstatus), .tx_clkout(tx_clkout),
.pll_locked(pll_locked), .rx_dataout(rx_dataout)// synopsys translate_off
        ,
        .aeq_fromgxb (),
        .aeq_togxb (),
        .cal_blk_calibrationstatus (),
        .cal_blk_powerdown (),
        .coreclkout (),
        .fixedclk (),
        .hip_tx_clkout(),
        .pipe8b10binvpolarity (),
        .pipedatavalid (),
        .pipeelecidle (),
        .pipephydonestatus (),
        .pipestatus (),
        .pll_powerdown (),
        .powerdn (),
        .rateswitch (),
        .rateswitchbaseclock (),
        .reconfig_fromgxb_oe (),
        .reconfig_clk (),
        .reconfig_fromgxb (),
        .reconfig_togxb (),
        .rx_a1a2size (),
        .rx_a1a2sizeout (),
        .rx_a1detect (),
        .rx_a2detect (),
        .rx_bistdone (),
        .rx_bisterr (),
        .rx_bitslip (),
        .rx_byteorderalignstatus (),
        .rx_channelaligned (),
        .rx_dataoutfull (),
        .rx_elecidleinfersel (),
        .rx_enabyteord (),
        .rx_k1detect (),
        .rx_k2detect (),
        .rx_locktodata (),
        .rx_locktorefclk (),
        .rx_phfifooverflow (),
        .rx_phfifordenable (),
        .rx_phfiforeset (),
        .rx_phfifounderflow (),
        .rx_phfifowrdisable (),
        .rx_pipebufferstat (),
        .rx_powerdown (),
        .rx_prbscidenable (),
        .rx_recovclkout (),
        .rx_revbyteorderwa (),
        .rx_rmfifoalmostempty (),
        .rx_rmfifoalmostfull (),
        .rx_rmfifodatadeleted (),
        .rx_rmfifodatainserted (),
        .rx_rmfifoempty (),
        .rx_rmfifofull (),
        .rx_rmfifordena (),
        .rx_rmfiforeset (),
        .rx_rmfifowrena (),
        .rx_runningdisp (),
        .rx_signaldetect (),
        .scanclk (),
        .scanin (),
        .scanmode (),
        .scanshift (),
        .testin (),
        .tx_datainfull (),
        .tx_detectrxloop (),
        .tx_dispval (),
        .tx_forcedisp (),
        .tx_forcedispcompliance (),
        .tx_forceelecidle (),
        .tx_invpolarity (),
        .tx_phfifooverflow (),
        .tx_phfiforeset (),
        .tx_phfifounderflow (),
        .tx_pipedeemph (),
        .tx_pipemargin (),
        .tx_pipeswing (),
        .tx_pllreset (),
        .tx_revparallellpbken ()
        // synopsys translate_on

);

defparam alt4gxb_component.starting_channel_number=0,
alt4gxb_component.equalizer_ctrl_a_setting=0,
alt4gxb_component.equalizer_ctrl_b_setting=0,
alt4gxb_component.equalizer_ctrl_c_setting=0,
alt4gxb_component.equalizer_ctrl_d_setting=0,
alt4gxb_component.equalizer_ctrl_v_setting=0,
alt4gxb_component.equalizer_dcgain_setting=1,
alt4gxb_component.intended_device_family="Stratix IV",
alt4gxb_component.loopback_mode="slb",
alt4gxb_component.lpm_hint="CBX_HDL_LANGUAGE=Verilog",
//make simgen working

alt4gxb_component.lpm_type="alt4gxb",
alt4gxb_component.number_of_channels=4,
alt4gxb_component.operation_mode="duplex",
alt4gxb_component.preemphasis_ctrl_1stposttap_setting=0,
alt4gxb_component.preemphasis_ctrl_2ndposttap_inv_setting="false",
alt4gxb_component.preemphasis_ctrl_2ndposttap_setting=0,
alt4gxb_component.preemphasis_ctrl_pretap_inv_setting="false",
alt4gxb_component.preemphasis_ctrl_pretap_setting=0,
alt4gxb_component.protocol="basic",
alt4gxb_component.receiver_termination="oct_100_ohms",
alt4gxb_component.reconfig_dprio_mode=0,
alt4gxb_component.reconfig_calibration="true",
alt4gxb_component.reconfig_fromgxb_port_width=17,
alt4gxb_component.reconfig_togxb_port_width=4,
alt4gxb_component.rx_8b_10b_mode="cascaded",
alt4gxb_component.rx_align_pattern="0101111100",
alt4gxb_component.rx_align_pattern_length=10,
alt4gxb_component.rx_allow_align_polarity_inversion="true",
alt4gxb_component.rx_allow_pipe_polarity_inversion="false",
alt4gxb_component.rx_bitslip_enable="false",
alt4gxb_component.rx_byte_ordering_mode="NONE",
alt4gxb_component.rx_channel_width=32,
alt4gxb_component.rx_common_mode="0.82v",
alt4gxb_component.rx_cru_bandwidth_type="Low",
alt4gxb_component.rx_cru_inclock0_period=8000,
alt4gxb_component.rx_datapath_low_latency_mode="false",
alt4gxb_component.rx_datapath_protocol="basic",
alt4gxb_component.rx_data_rate=5000,
alt4gxb_component.rx_data_rate_remainder=0,
alt4gxb_component.rx_digitalreset_port_width=4,
alt4gxb_component.rx_enable_bit_reversal="false",
alt4gxb_component.rx_enable_deep_align_byte_swap="false",
alt4gxb_component.rx_enable_lock_to_data_sig="false",
alt4gxb_component.rx_enable_lock_to_refclk_sig="false",
alt4gxb_component.rx_flip_rx_out="false",
alt4gxb_component.rx_force_signal_detect="true",
alt4gxb_component.rx_ppmselect=32,
alt4gxb_component.rx_rate_match_fifo_mode="none",
alt4gxb_component.rx_rate_match_back_to_back="false",
alt4gxb_component.rx_run_length=10,
alt4gxb_component.rx_run_length_enable="true",
alt4gxb_component.rx_signal_detect_threshold=2,
alt4gxb_component.rx_use_align_state_machine="true",
alt4gxb_component.rx_use_clkout="true",
alt4gxb_component.rx_use_coreclk="true",
alt4gxb_component.rx_use_cruclk="true",
alt4gxb_component.rx_use_deserializer_double_data_mode="true",
alt4gxb_component.rx_use_deskew_fifo="false",
alt4gxb_component.rx_use_double_data_mode="true",
alt4gxb_component.rx_use_rising_edge_triggered_pattern_align="true",
alt4gxb_component.transmitter_termination="oct_100_ohms",
alt4gxb_component.tx_8b_10b_mode="cascaded",
alt4gxb_component.tx_allow_polarity_inversion="false",
alt4gxb_component.tx_analog_power="AUTO",
alt4gxb_component.tx_channel_width=32,
alt4gxb_component.tx_common_mode="0.65v",
alt4gxb_component.tx_datapath_low_latency_mode="false",
alt4gxb_component.tx_data_rate=5000,
alt4gxb_component.tx_data_rate_remainder=0,
alt4gxb_component.tx_digitalreset_port_width=4,
alt4gxb_component.tx_enable_bit_reversal="false",
alt4gxb_component.tx_flip_tx_in="false",
alt4gxb_component.tx_force_disparity_mode="false",
alt4gxb_component.tx_pll_bandwidth_type="Low",
alt4gxb_component.tx_pll_inclk0_period=8000,
alt4gxb_component.tx_transmit_protocol="basic",
alt4gxb_component.tx_use_coreclk="true",
alt4gxb_component.tx_use_double_data_mode="true",
alt4gxb_component.tx_use_serializer_double_data_mode="true",
alt4gxb_component.use_calibration_block="true",
alt4gxb_component.vod_ctrl_setting=7,
alt4gxb_component.gxb_analog_power="AUTO",
alt4gxb_component.gxb_powerdown_width=1,
alt4gxb_component.number_of_quads=1,
alt4gxb_component.rx_cru_data_rate=2000,
alt4gxb_component.rx_cru_divide_by=1,
alt4gxb_component.rx_cru_m_divider=0,
alt4gxb_component.rx_cru_multiply_by=5,
alt4gxb_component.rx_cru_n_divider=1,
alt4gxb_component.rx_cru_pfd_clk_select=0,
alt4gxb_component.rx_cru_vco_post_scale_divider=4,
alt4gxb_component.rx_dwidth_factor=4,
alt4gxb_component.rx_word_aligner_num_byte=2,
alt4gxb_component.tx_dwidth_factor=4,
alt4gxb_component.tx_pll_clock_post_divider=4,
alt4gxb_component.tx_pll_data_rate=2000,
alt4gxb_component.tx_pll_divide_by=1,
alt4gxb_component.tx_pll_m_divider=0,
alt4gxb_component.tx_pll_multiply_by=5,
alt4gxb_component.tx_pll_n_divider=1,
alt4gxb_component.tx_pll_pfd_clk_select=0,
alt4gxb_component.tx_pll_vco_post_scale_divider=1,
alt4gxb_component.tx_0ppm_core_clock="true",
alt4gxb_component.rx_0ppm_core_clock="true",
alt4gxb_component.pll_control_width=1,
alt4gxb_component.tx_clkout_width=4,
alt4gxb_component.effective_data_rate="5000 Mbps",
alt4gxb_component.input_clock_frequency="125.0 MHz";

endmodule
// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ALT_SIMLIB_GEN STRING "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Stratix IV"
// Retrieval info: PRIVATE: NUM_KEYS NUMERIC "69"
// Retrieval info: PRIVATE: RECONFIG_PROTOCOL STRING "BASIC"
// Retrieval info: PRIVATE: RECONFIG_SUBPROTOCOL STRING "none"
// Retrieval info: PRIVATE: RX_ENABLE_DC_COUPLING STRING "false"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "0"
// Retrieval info: PRIVATE: WIZ_DATA_RATE STRING "5000"
// Retrieval info: PRIVATE: WIZ_DPRIO_INCLK_FREQ_ARRAY STRING "250.0 200.0 125.0 125.0"
// Retrieval info: PRIVATE: WIZ_DPRIO_INPUT_A STRING "2000"
// Retrieval info: PRIVATE: WIZ_DPRIO_INPUT_A_UNIT STRING "Mbps"
// Retrieval info: PRIVATE: WIZ_DPRIO_INPUT_B STRING "250.0"
// Retrieval info: PRIVATE: WIZ_DPRIO_INPUT_B_UNIT STRING "MHz"
// Retrieval info: PRIVATE: WIZ_DPRIO_INPUT_SELECTION NUMERIC "0"
// Retrieval info: PRIVATE: WIZ_DPRIO_REF_CLK0_FREQ STRING "125.0"
// Retrieval info: PRIVATE: WIZ_DPRIO_REF_CLK0_PROTOCOL STRING "Basic"
// Retrieval info: PRIVATE: WIZ_DPRIO_REF_CLK1_FREQ STRING "250"
// Retrieval info: PRIVATE: WIZ_DPRIO_REF_CLK1_PROTOCOL STRING "Basic"
// Retrieval info: PRIVATE: WIZ_DPRIO_REF_CLK2_FREQ STRING "250"
// Retrieval info: PRIVATE: WIZ_DPRIO_REF_CLK2_PROTOCOL STRING "Basic"
// Retrieval info: PRIVATE: WIZ_DPRIO_REF_CLK3_FREQ STRING "250"
// Retrieval info: PRIVATE: WIZ_DPRIO_REF_CLK3_PROTOCOL STRING "Basic"
// Retrieval info: PRIVATE: WIZ_DPRIO_REF_CLK4_FREQ STRING "250"
// Retrieval info: PRIVATE: WIZ_DPRIO_REF_CLK4_PROTOCOL STRING "Basic"
// Retrieval info: PRIVATE: WIZ_DPRIO_REF_CLK5_FREQ STRING "250"
// Retrieval info: PRIVATE: WIZ_DPRIO_REF_CLK5_PROTOCOL STRING "Basic"
// Retrieval info: PRIVATE: WIZ_DPRIO_REF_CLK6_FREQ STRING "250"
// Retrieval info: PRIVATE: WIZ_DPRIO_REF_CLK6_PROTOCOL STRING "Basic"
// Retrieval info: PRIVATE: WIZ_ENABLE_EQUALIZER_CTRL NUMERIC "1"
// Retrieval info: PRIVATE: WIZ_EQUALIZER_CTRL_SETTING NUMERIC "0"
// Retrieval info: PRIVATE: WIZ_FORCE_DEFAULT_SETTINGS NUMERIC "0"
// Retrieval info: PRIVATE: WIZ_INCLK_FREQ STRING "125.0"
// Retrieval info: PRIVATE: WIZ_INCLK_FREQ_ARRAY STRING "125.0 125.0 62.5 50.0"
// Retrieval info: PRIVATE: WIZ_INPUT_A STRING "5000"
// Retrieval info: PRIVATE: WIZ_INPUT_A_UNIT STRING "Mbps"
// Retrieval info: PRIVATE: WIZ_INPUT_B STRING "125.0"
// Retrieval info: PRIVATE: WIZ_INPUT_B_UNIT STRING "MHz"
// Retrieval info: PRIVATE: WIZ_INPUT_SELECTION NUMERIC "0"
// Retrieval info: PRIVATE: WIZ_PROTOCOL STRING "Basic"
// Retrieval info: PRIVATE: WIZ_RX_VCM STRING "0.85"
// Retrieval info: PRIVATE: WIZ_SUBPROTOCOL STRING "None"
// Retrieval info: PRIVATE: WIZ_TX_VCM STRING "0.6"
// Retrieval info: PRIVATE: WIZ_VCCHTX STRING "AUTO"
// Retrieval info: PRIVATE: WIZ_WORD_ALIGN_FLIP_PATTERN STRING "0"
// Retrieval info: PARAMETER: STARTING_CHANNEL_NUMBER NUMERIC "0"
// Retrieval info: CONSTANT: CMU_PLL_INCLOCK_PERIOD NUMERIC "8000"
// Retrieval info: CONSTANT: CMU_PLL_LOOP_FILTER_RESISTOR_CONTROL NUMERIC "1"
// Retrieval info: CONSTANT: DIGITALRESET_PORT_WIDTH NUMERIC "4"
// Retrieval info: CONSTANT: EN_LOCAL_CLK_DIV_CTRL STRING "true"
// Retrieval info: CONSTANT: EQUALIZER_CTRL_A_SETTING NUMERIC "0"
// Retrieval info: CONSTANT: EQUALIZER_CTRL_B_SETTING NUMERIC "0"
// Retrieval info: CONSTANT: EQUALIZER_CTRL_C_SETTING NUMERIC "0"
// Retrieval info: CONSTANT: EQUALIZER_CTRL_D_SETTING NUMERIC "0"
// Retrieval info: CONSTANT: EQUALIZER_CTRL_V_SETTING NUMERIC "0"
// Retrieval info: CONSTANT: EQUALIZER_DCGAIN_SETTING NUMERIC "1"
// Retrieval info: CONSTANT: GEN_RECONFIG_PLL STRING "false"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Stratix IV"
// Retrieval info: CONSTANT: LOOPBACK_MODE STRING "slb"
// Retrieval info: CONSTANT: LPM_TYPE STRING "alt4gxb"
// Retrieval info: CONSTANT: NUMBER_OF_CHANNELS NUMERIC "4"
// Retrieval info: CONSTANT: OPERATION_MODE STRING "duplex"
// Retrieval info: CONSTANT: PREEMPHASIS_CTRL_1STPOSTTAP_SETTING NUMERIC "0"
// Retrieval info: CONSTANT: PREEMPHASIS_CTRL_2NDPOSTTAP_INV_SETTING STRING "false"
// Retrieval info: CONSTANT: PREEMPHASIS_CTRL_2NDPOSTTAP_SETTING NUMERIC "0"
// Retrieval info: CONSTANT: PREEMPHASIS_CTRL_PRETAP_INV_SETTING STRING "false"
// Retrieval info: CONSTANT: PREEMPHASIS_CTRL_PRETAP_SETTING NUMERIC "0"
// Retrieval info: CONSTANT: PROTOCOL STRING "basic"
// Retrieval info: CONSTANT: RECEIVER_TERMINATION STRING "oct_100_ohms"
// Retrieval info: CONSTANT: RECONFIG_DPRIO_MODE NUMERIC "1"
// Retrieval info: CONSTANT: REVERSE_LOOPBACK_MODE STRING "none"
// Retrieval info: CONSTANT: RX_8B_10B_COMPATIBILITY_MODE STRING "true"
// Retrieval info: CONSTANT: RX_8B_10B_MODE STRING "cascaded"
// Retrieval info: CONSTANT: RX_ALIGN_PATTERN STRING "0101111100"
// Retrieval info: CONSTANT: RX_ALIGN_PATTERN_LENGTH NUMERIC "10"
// Retrieval info: CONSTANT: RX_ALLOW_ALIGN_POLARITY_INVERSION STRING "true"
// Retrieval info: CONSTANT: RX_ALLOW_PIPE_POLARITY_INVERSION STRING "false"
// Retrieval info: CONSTANT: RX_BANDWIDTH_MODE NUMERIC "3"
// Retrieval info: CONSTANT: RX_BITSLIP_ENABLE STRING "false"
// Retrieval info: CONSTANT: RX_BYTE_ORDERING_MODE STRING "none"
// Retrieval info: CONSTANT: RX_CHANNEL_WIDTH NUMERIC "32"
// Retrieval info: CONSTANT: RX_COMMON_MODE STRING "0.9v"
// Retrieval info: CONSTANT: RX_CRU_INCLOCK_PERIOD NUMERIC "8000"
// Retrieval info: CONSTANT: RX_CRU_PRE_DIVIDE_BY NUMERIC "1"
// Retrieval info: CONSTANT: RX_DATAPATH_PROTOCOL STRING "basic"
// Retrieval info: CONSTANT: RX_DATA_RATE NUMERIC "5000"
// Retrieval info: CONSTANT: RX_DATA_RATE_REMAINDER NUMERIC "0"
// Retrieval info: CONSTANT: RX_DISABLE_AUTO_IDLE_INSERTION STRING "false"
// Retrieval info: CONSTANT: RX_ENABLE_BIT_REVERSAL STRING "false"
// Retrieval info: CONSTANT: RX_ENABLE_DEEP_ALIGN_BYTE_SWAP STRING "false"
// Retrieval info: CONSTANT: RX_ENABLE_LOCK_TO_DATA_SIG STRING "false"
// Retrieval info: CONSTANT: RX_ENABLE_LOCK_TO_REFCLK_SIG STRING "false"
// Retrieval info: CONSTANT: RX_ENABLE_SELF_TEST_MODE STRING "false"
// Retrieval info: CONSTANT: RX_ENABLE_TRUE_COMPLEMENT_MATCH_IN_WORD_ALIGN STRING "true"
// Retrieval info: CONSTANT: RX_FLIP_RX_OUT STRING "false"
// Retrieval info: CONSTANT: RX_FORCE_SIGNAL_DETECT STRING "true"
// Retrieval info: CONSTANT: RX_PPMSELECT NUMERIC "32"
// Retrieval info: CONSTANT: RX_RATE_MATCH_FIFO_MODE STRING "none"
// Retrieval info: CONSTANT: RX_RUN_LENGTH NUMERIC "10"
// Retrieval info: CONSTANT: RX_RUN_LENGTH_ENABLE STRING "true"
// Retrieval info: CONSTANT: RX_SIGNAL_DETECT_THRESHOLD NUMERIC "2"
// Retrieval info: CONSTANT: RX_USE_ALIGN_STATE_MACHINE STRING "true"
// Retrieval info: CONSTANT: RX_USE_CLKOUT STRING "true"
// Retrieval info: CONSTANT: RX_USE_CORECLK STRING "true"
// Retrieval info: CONSTANT: RX_USE_CRUCLK STRING "true"
// Retrieval info: CONSTANT: RX_USE_DESERIALIZER_DOUBLE_DATA_MODE STRING "true"
// Retrieval info: CONSTANT: RX_USE_DESKEW_FIFO STRING "false"
// Retrieval info: CONSTANT: RX_USE_DOUBLE_DATA_MODE STRING "true"
// Retrieval info: CONSTANT: RX_USE_RISING_EDGE_TRIGGERED_PATTERN_ALIGN STRING "true"
// Retrieval info: CONSTANT: TRANSMITTER_TERMINATION STRING "oct_100_ohms"
// Retrieval info: CONSTANT: TX_8B_10B_COMPATIBILITY_MODE STRING "true"
// Retrieval info: CONSTANT: TX_8B_10B_MODE STRING "cascaded"
// Retrieval info: CONSTANT: TX_ALLOW_POLARITY_INVERSION STRING "false"
// Retrieval info: CONSTANT: TX_ANALOG_POWER STRING "AUTO"
// Retrieval info: CONSTANT: TX_CHANNEL_WIDTH NUMERIC "32"
// Retrieval info: CONSTANT: TX_COMMON_MODE STRING "0.6v"
// Retrieval info: CONSTANT: TX_DATA_RATE NUMERIC "5000"
// Retrieval info: CONSTANT: TX_DATA_RATE_REMAINDER NUMERIC "0"
// Retrieval info: CONSTANT: TX_ENABLE_BIT_REVERSAL STRING "false"
// Retrieval info: CONSTANT: TX_ENABLE_IDLE_SELECTION STRING "false"
// Retrieval info: CONSTANT: TX_ENABLE_SELF_TEST_MODE STRING "false"
// Retrieval info: CONSTANT: TX_FLIP_TX_IN STRING "false"
// Retrieval info: CONSTANT: TX_FORCE_DISPARITY_MODE STRING "false"
// Retrieval info: CONSTANT: TX_REFCLK_DIVIDE_BY NUMERIC "1"
// Retrieval info: CONSTANT: TX_TRANSMIT_PROTOCOL STRING "basic"
// Retrieval info: CONSTANT: TX_USE_CORECLK STRING "true"
// Retrieval info: CONSTANT: TX_USE_DOUBLE_DATA_MODE STRING "true"
// Retrieval info: CONSTANT: TX_USE_SERIALIZER_DOUBLE_DATA_MODE STRING "true"
// Retrieval info: CONSTANT: USE_CALIBRATION_BLOCK STRING "true"
// Retrieval info: CONSTANT: VOD_CTRL_SETTING NUMERIC "7"
// Retrieval info: CONSTANT: tx_0ppm_core_clock STRING "true"
// Retrieval info: CONSTANT: rx_0ppm_core_clock STRING "true"
// Retrieval info: USED_PORT: cal_blk_clk 0 0 0 0 INPUT NODEFVAL "cal_blk_clk"
// Retrieval info: USED_PORT: debug_rx_phase_comp_fifo_error 0 0 4 0 OUTPUT NODEFVAL "debug_rx_phase_comp_fifo_error[0..0]"
// Retrieval info: USED_PORT: debug_tx_phase_comp_fifo_error 0 0 4 0 OUTPUT NODEFVAL "debug_tx_phase_comp_fifo_error[0..0]"
// Retrieval info: USED_PORT: gxb_enable 0 0 1 0 INPUT NODEFVAL "gxb_enable[0..0]"
// Retrieval info: USED_PORT: gxb_powerdown 0 0 1 0 INPUT NODEFVAL "gxb_powerdown[0..0]"
// Retrieval info: USED_PORT: pll_inclk 0 0 0 0 INPUT NODEFVAL "pll_inclk"
// Retrieval info: USED_PORT: pll_locked 0 0 1 0 OUTPUT NODEFVAL "pll_locked[0..0]"
// Retrieval info: USED_PORT: reconfig_clk 0 0 0 0 INPUT NODEFVAL "reconfig_clk"
// Retrieval info: USED_PORT: reconfig_fromgxb 0 0 1 0 OUTPUT NODEFVAL "reconfig_fromgxb[0..0]"
// Retrieval info: USED_PORT: reconfig_togxb 0 0 3 0 INPUT NODEFVAL "reconfig_togxb[2..0]"
// Retrieval info: USED_PORT: rx_analogreset 0 0 4 0 INPUT NODEFVAL "rx_analogreset[0..0]"
// Retrieval info: USED_PORT: rx_clkout 0 0 4 0 OUTPUT NODEFVAL "rx_clkout[0..0]"
// Retrieval info: USED_PORT: rx_coreclk 0 0 4 0 INPUT NODEFVAL "rx_coreclk[0..0]"
// Retrieval info: USED_PORT: rx_cruclk 0 0 4 0 INPUT GND "rx_cruclk[0..0]"
// Retrieval info: USED_PORT: rx_ctrldetect 0 0 16 0 OUTPUT NODEFVAL "rx_ctrldetect[0..0]"
// Retrieval info: USED_PORT: rx_datain 0 0 4 0 INPUT NODEFVAL "rx_datain[0..0]"
// Retrieval info: USED_PORT: rx_dataout 0 0 128 0 OUTPUT NODEFVAL "rx_dataout[7..0]"
// Retrieval info: USED_PORT: rx_digitalreset 0 0 4 0 INPUT NODEFVAL "rx_digitalreset[0..0]"
// Retrieval info: USED_PORT: rx_disperr 0 0 16 0 OUTPUT NODEFVAL "rx_disperr[0..0]"
// Retrieval info: USED_PORT: rx_enapatternalign 0 0 4 0 INPUT NODEFVAL "rx_enapatternalign[0..0]"
// Retrieval info: USED_PORT: rx_errdetect 0 0 16 0 OUTPUT NODEFVAL "rx_errdetect[0..0]"
// Retrieval info: USED_PORT: rx_freqlocked 0 0 4 0 OUTPUT NODEFVAL "rx_freqlocked[0..0]"
// Retrieval info: USED_PORT: rx_invpolarity 0 0 4 0 INPUT NODEFVAL "rx_invpolarity[0..0]"
// Retrieval info: USED_PORT: rx_patterndetect 0 0 16 0 OUTPUT NODEFVAL "rx_patterndetect[0..0]"
// Retrieval info: USED_PORT: rx_pll_locked 0 0 4 0 OUTPUT NODEFVAL "rx_pll_locked[0..0]"
// Retrieval info: USED_PORT: rx_rlv 0 0 4 0 OUTPUT NODEFVAL "rx_rlv[0..0]"
// Retrieval info: USED_PORT: rx_seriallpbken 0 0 4 0 INPUT NODEFVAL "rx_seriallpbken[0..0]"
// Retrieval info: USED_PORT: rx_syncstatus 0 0 16 0 OUTPUT NODEFVAL "rx_syncstatus[0..0]"
// Retrieval info: USED_PORT: tx_clkout 0 0 4 0 OUTPUT NODEFVAL "tx_clkout[0..0]"
// Retrieval info: USED_PORT: tx_coreclk 0 0 4 0 INPUT NODEFVAL "tx_coreclk[0..0]"
// Retrieval info: USED_PORT: tx_ctrlenable 0 0 16 0 INPUT NODEFVAL "tx_ctrlenable[0..0]"
// Retrieval info: USED_PORT: tx_datain 0 0 128 0 INPUT NODEFVAL "tx_datain[7..0]"
// Retrieval info: USED_PORT: tx_dataout 0 0 4 0 OUTPUT NODEFVAL "tx_dataout[0..0]"
// Retrieval info: USED_PORT: tx_digitalreset 0 0 4 0 INPUT NODEFVAL "tx_digitalreset[0..0]"
// Retrieval info: CONNECT: rx_patterndetect 0 0 16 0 @rx_patterndetect 0 0 16 0
// Retrieval info: CONNECT: @rx_invpolarity 0 0 4 0 rx_invpolarity 0 0 4 0
// Retrieval info: CONNECT: @rx_analogreset 0 0 4 0 rx_analogreset 0 0 4 0
// Retrieval info: CONNECT: rx_ctrldetect 0 0 16 0 @rx_ctrldetect 0 0 16 0
// Retrieval info: CONNECT: @gxb_powerdown 0 0 1 0 gxb_powerdown 0 0 1 0
// Retrieval info: CONNECT: rx_dataout 0 0 128 0 @rx_dataout 0 0 128 0
// Retrieval info: CONNECT: @cal_blk_clk 0 0 0 0 cal_blk_clk 0 0 0 0
// Retrieval info: CONNECT: rx_errdetect 0 0 16 0 @rx_errdetect 0 0 16 0
// Retrieval info: CONNECT: @rx_enapatternalign 0 0 4 0 rx_enapatternalign 0 0 4 0
// Retrieval info: CONNECT: @tx_coreclk 0 0 4 0 tx_coreclk 0 0 4 0
// Retrieval info: CONNECT: @tx_digitalreset 0 0 4 0 tx_digitalreset 0 0 4 0
// Retrieval info: CONNECT: rx_pll_locked 0 0 4 0 @rx_pll_locked 0 0 4 0
// Retrieval info: CONNECT: @rx_revbitorderwa 0 0 1 0 GND 0 0 1 0
// Retrieval info: CONNECT: rx_syncstatus 0 0 16 0 @rx_syncstatus 0 0 16 0
// Retrieval info: CONNECT: @rx_seriallpbken 0 0 4 0 rx_seriallpbken 0 0 4 0
// Retrieval info: CONNECT: @reconfig_clk 0 0 0 0 reconfig_clk 0 0 0 0
// Retrieval info: CONNECT: rx_clkout 0 0 4 0 @rx_clkout 0 0 4 0
// Retrieval info: CONNECT: @rx_coreclk 0 0 4 0 rx_coreclk 0 0 4 0
// Retrieval info: CONNECT: @reconfig_togxb 0 0 3 0 reconfig_togxb 0 0 3 0
// Retrieval info: CONNECT: pll_locked 0 0 1 0 @pll_locked 0 0 1 0
// Retrieval info: CONNECT: @rx_digitalreset 0 0 4 0 rx_digitalreset 0 0 4 0
// Retrieval info: CONNECT: tx_clkout 0 0 4 0 @tx_clkout 0 0 4 0
// Retrieval info: CONNECT: @rx_cruclk 0 0 4 0 rx_cruclk 0 0 4 0
// Retrieval info: CONNECT: debug_rx_phase_comp_fifo_error 0 0 4 0 @debug_rx_phase_comp_fifo_error 0 0 4 0
// Retrieval info: CONNECT: rx_rlv 0 0 4 0 @rx_rlv 0 0 4 0
// Retrieval info: CONNECT: @pll_inclk 0 0 0 0 pll_inclk 0 0 0 0
// Retrieval info: CONNECT: @tx_ctrlenable 0 0 16 0 tx_ctrlenable 0 0 16 0
// Retrieval info: CONNECT: tx_dataout 0 0 4 0 @tx_dataout 0 0 4 0
// Retrieval info: CONNECT: @tx_datain 0 0 128 0 tx_datain 0 0 128 0
// Retrieval info: CONNECT: reconfig_fromgxb 0 0 1 0 @reconfig_fromgxb 0 0 1 0
// Retrieval info: CONNECT: @gxb_enable 0 0 1 0 gxb_enable 0 0 1 0
// Retrieval info: CONNECT: rx_freqlocked 0 0 4 0 @rx_freqlocked 0 0 4 0
// Retrieval info: CONNECT: @rx_datain 0 0 4 0 rx_datain 0 0 4 0
// Retrieval info: CONNECT: rx_disperr 0 0 16 0 @rx_disperr 0 0 16 0
// Retrieval info: CONNECT: debug_tx_phase_comp_fifo_error 0 0 4 0 @debug_tx_phase_comp_fifo_error 0 0 1 0
// Retrieval info: GEN_FILE: TYPE_NORMAL four_lane_seriallite_and_physlite2_xcvr.v TRUE FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL four_lane_seriallite_and_physlite2_xcvr.inc FALSE FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL four_lane_seriallite_and_physlite2_xcvr.cmp FALSE FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL four_lane_seriallite_and_physlite2_xcvr.bsf FALSE FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL four_lane_seriallite_and_physlite2_xcvr_inst.v FALSE FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL four_lane_seriallite_and_physlite2_xcvr_bb.v FALSE FALSE

