serialite_xcvr_priority_only_inst
 (
	.rxin                         ( rxin                        ),
	.ctrl_tc_force_train          ( ctrl_tc_force_train         ),
	.trefclk                      ( trefclk                     ),
	.cal_blk_clk                  ( cal_blk_clk                 ),
	.gxb_powerdown                ( gxb_powerdown               ),
	.mreset_n                     ( mreset_n                    ),
	.rxhpp_clk                    ( rxhpp_clk                   ),
	.rxhpp_ena                    ( rxhpp_ena                   ),
	.ctl_rxhpp_ftl                ( ctl_rxhpp_ftl               ),
	.ctl_rxhpp_eopdav             ( ctl_rxhpp_eopdav            ),
	.txhpp_clk                    ( txhpp_clk                   ),
	.txhpp_ena                    ( txhpp_ena                   ),
	.txhpp_sop                    ( txhpp_sop                   ),
	.txhpp_eop                    ( txhpp_eop                   ),
	.txhpp_err                    ( txhpp_err                   ),
	.txhpp_mty                    ( txhpp_mty                   ),
	.txhpp_dat                    ( txhpp_dat                   ),
	.txhpp_adr                    ( txhpp_adr                   ),
	.ctl_txhpp_fth                ( ctl_txhpp_fth               ),
	.ctrl_tc_serial_lpbena        ( ctrl_tc_serial_lpbena       ),
	.reconfig_clk                 ( reconfig_clk                ),
	.reconfig_togxb               ( reconfig_togxb              ),
	.rrefclk                      ( rrefclk                     ),
	.stat_rr_link                 ( stat_rr_link                ),
	.txout                        ( txout                       ),
	.stat_tc_pll_locked           ( stat_tc_pll_locked          ),
	.tx_coreclock                 ( tx_coreclock                ),
	.rcvd_clk_out                 ( rcvd_clk_out                ),
	.err_rr_8berrdet              ( err_rr_8berrdet             ),
	.err_rr_disp                  ( err_rr_disp                 ),
	.err_rr_pcfifo_uflw           ( err_rr_pcfifo_uflw          ),
	.err_rr_pcfifo_oflw           ( err_rr_pcfifo_oflw          ),
	.err_rr_rlv                   ( err_rr_rlv                  ),
	.stat_rr_gxsync               ( stat_rr_gxsync              ),
	.stat_rr_freqlock             ( stat_rr_freqlock            ),
	.stat_rr_rxlocked             ( stat_rr_rxlocked            ),
	.stat_rr_pattdet              ( stat_rr_pattdet             ),
	.rxhpp_sop                    ( rxhpp_sop                   ),
	.rxhpp_eop                    ( rxhpp_eop                   ),
	.rxhpp_err                    ( rxhpp_err                   ),
	.rxhpp_mty                    ( rxhpp_mty                   ),
	.rxhpp_dat                    ( rxhpp_dat                   ),
	.rxhpp_adr                    ( rxhpp_adr                   ),
	.rxhpp_val                    ( rxhpp_val                   ),
	.rxhpp_dav                    ( rxhpp_dav                   ),
	.stat_rxhpp_empty             ( stat_rxhpp_empty            ),
	.err_tc_rxhpp_oflw            ( err_tc_rxhpp_oflw           ),
	.err_tc_pcfifo_oflw           ( err_tc_pcfifo_oflw          ),
	.err_tc_pcfifo_uflw           ( err_tc_pcfifo_uflw          ),
	.err_txhpp_oflw               ( err_txhpp_oflw              ),
	.txhpp_dav                    ( txhpp_dav                   ),
	.reconfig_fromgxb             ( reconfig_fromgxb            ),
	.stat_tc_rst_done             ( stat_tc_rst_done            ),
	.err_rr_foffre_oflw           ( err_rr_foffre_oflw          ),
	.stat_tc_foffre_empty         ( stat_tc_foffre_empty        ),
	.stat_rr_ebprx                ( stat_rr_ebprx               ),
	.err_rr_bip8                  ( err_rr_bip8                 ),
	.err_rr_crc                   ( err_rr_crc                  ),
  //.err_rr_fcrx_bne              ( err_rr_fcrx_bne             ),
  //.err_rr_roerx_bne             ( err_rr_roerx_bne            ),
	.err_rr_invalid_lmprx         ( err_rr_invalid_lmprx        ),
	.err_rr_missing_start_dcw     ( err_rr_missing_start_dcw    ),
	.err_rr_addr_mismatch         ( err_rr_addr_mismatch        ),
	.err_rr_pol_rev_required      ( err_rr_pol_rev_required     ),
	.err_tc_roe_rsnd_gt4          ( err_tc_roe_rsnd_gt4         ),
	.stat_tc_roe_timeout          ( stat_tc_roe_timeout         ),
	.stat_rr_roe_ack              ( stat_rr_roe_ack             ),
	.stat_rr_roe_nack             ( stat_rr_roe_nack            ),
    .err_tc_is_drop               (err_tc_is_drop               ),
    .err_tc_lm_fifo_oflw          (err_tc_lm_fifo_oflw          ),
    .err_rr_rx2txfifo_oflw        (err_rr_rx2txfifo_oflw        ),
	.stat_rr_fc_rdp_valid(stat_rr_fc_rdp_valid),
	.stat_rr_fc_hpp_valid(stat_rr_fc_hpp_valid),
	.stat_rr_fc_value(stat_rr_fc_value),
	.stat_tc_fc_rdp_retransmit(stat_tc_fc_rdp_retransmit),
	.stat_tc_fc_hpp_retransmit(stat_tc_fc_hpp_retransmit),
	.stat_tc_rdp_thresh_breach(stat_tc_rdp_thresh_breach),
	.stat_tc_hpp_thresh_breach(stat_tc_hpp_thresh_breach)
	
	);