`ifndef UART_REGFILE_TYPES_V
`define UART_REGFILE_TYPES_V
`ifdef SOFTWARE_IS_QUARTUS
package uart_regfile_types;
`endif
     localparam GENERIC_UART_REGFILE = 0;
     localparam BERC_CTRL_UART_REGFILE = 1;
	 localparam DESERIALIZER_CTRL_UART_REGFILE = 2;
	 localparam SPARTAN_ADC_CTRL_UART_REGFILE = 3;
	 localparam FMC_MCS_UART_REGFILE = 4;
	 localparam BOARD_MGMT_UART_REGFILE = 5;	 
	 localparam GRIF16_ADC_DESER_AND_DAC_CTRL_REGFILE = 6;
	 localparam SERIALLITE_PRIORITY_PACKETS_CTRL_REGFILE = 7;
	 localparam GRIFC_SLAVE_CTRL_REGFILE = 8;
	 localparam TOP_LEVEL_UART_REGFILE = 9;
	 localparam SECONDARY_TOP_LEVEL_UART_REGFILE = 10;
	 localparam PACKET_MUX_16_TO_1_AVALON_MM_MAPPED_UART_REGFILE = 11;
	 localparam MAXV_UART_REGFILE = 12;
	 localparam ADC12EU050_UART_REGFILE = 13;
	 localparam MPFE_UART_REGFILE = 14;
	 localparam	DEAP_DTM_TRIGGER_UART_REGFILE = 15;	 
	 localparam PACKET_MUX_8_TO_1_AVALON_MM_MAPPED_UART_REGFILE = 16;
	 localparam ARRIA_V_XCVR_PHY_CTRL_REGFILE = 17;
	 localparam ARRIA_V_JESD204B_TIADC12J4000_CTRL_REGFILE = 18;
	 localparam ARRIA_V_JESD204B_TIADC12J4000_DIAGNOSTIC_REGFILE = 19;
	 localparam AVSOC_JESD_ENCAPSULATOR_TOP_CTRL_REGFILE = 20;
	 localparam OPENCORES_SPI_UART_REGFILE = 21;
	 localparam OPENCORES_SPI_DIAGNOSTIC_UART_REGFILE = 22;
	 localparam LMK04828_OPENCORES_SPI_UART_REGFILE = 23;
	 localparam LMK04828_OPENCORES_SPI_DIAGNOSTIC_UART_REGFILE = 24;
	 localparam AD9680_OPENCORES_SPI_UART_REGFILE = 25;
	 localparam AD9680_OPENCORES_SPI_DIAGNOSTIC_UART_REGFILE = 26;
	 localparam JESD_CONTROL_UNIT_AVALON_MM_MAPPED_UART_REGFILE = 27;
	 localparam NIOS_DACS_STANDALONE_REGFILE = 28;
	 localparam JESD_NIOS_DACS_STANDALONE_REGFILE = 29;
	 localparam JESD_SYSREF_PLL_AVALON_MM_MAPPED_UART_REGFILE = 30;
 	 localparam ARRIA_V_SLITE_FOUR_LANE_XCVR_PHY_CTRL_REGFILE = 31;
	 localparam ARRIA_V_SLITE_FOUR_LANE_XCVR_RECONFIG_CTRL_REGFILE = 32;
     localparam ARRIA_V_SLITE_FOUR_LANE_DIAGNOSTIC_REGFILE = 33;
     localparam UDP_TEST_PACKET_GENERATOR_REGFILE = 34;
     localparam TOP_UDP_STREAMER_CTRL_REGFILE = 35;
     localparam STANDALONE_HW_UDP_DMA_UART_REGFILE = 36;
     localparam STRATIX_IV_FOUR_LANE_STREAMING_SLITE_REGFILE = 37;
     localparam ERROR_MONITOR_REGFILE = 38;
     localparam SLITE_ERROR_MONITOR_REGFILE = 39;
	 localparam RATE_MATCH_FIFO_REGFILE = 40;
	 localparam NIOS_MULTI_DAC_STANDALONE_REGFILE = 41;
	 localparam ZL9101M_UART_REGFILE = 42;
	 localparam AD9249_OPENCORES_SPI_UART_REGFILE = 43;
	 localparam AD9249_OPENCORES_SPI_DIAGNOSTIC_UART_REGFILE = 44;
	 localparam GENERIC_REFRAMER_REGFILE = 45;
	 localparam GENERIC_PARELLELIZER_2X_REGFILE = 46;
	 localparam DATA_ACQUISITION_TRIGGERED_FIFO = 47;
	 localparam CLOCK_RATE_MEASURE_REGFILE = 48;
	 localparam CLOCK_PHASE_LOCK_MONITOR_REGFILE = 49;
	 localparam LTC2983_UART_REGFILE = 50;
	 localparam TX8B10B_SIMPLE_LINK_REGFILE = 51;
	 localparam RX8B10B_SIMPLE_LINK_REGFILE = 52;
	 localparam LTC2380_IVC102_REGFILE = 53;
	// localparam STREAM_TO_DMA_REGFILE = 54;//reserved
	 localparam STREAM_TO_DMA_REGFILE = 55;
	 localparam MAX11000_UART_REGFILE = 56;
	 localparam JOINT_LTC2380_IVC102_MAX11000_UART_REGFILE = 57;
	 localparam UDP_PACKET_SPLITTER_UART_REGFILE = 58;
	 localparam MULTI_STREAM_PACKETIZER_UART_REGFILE = 59;
	 localparam MULTI_TEST_SIGNAL_GENERATOR_UART_REGFILE = 60;
	 localparam CLOCK_MEASURE_EXACT_UART_REGFILE = 63;
	 localparam EMBED_2_BIT_SERIAL_DATA_UART_REGFILE = 64;
	 localparam MULTI_SPI_SLAVE_RECEIVER_UART_REGFILE = 65;
	 localparam EMIF_EFFICIENCY_MONITOR_UART_REGFILE = 66;
	 localparam FFT_X4_UART_REGFILE = 67;
	 localparam CLOCK_MEASURE_AUTO_UART_REGFILE = 68;
	 localparam SPIRAL_FFT_X4_UART_REGFILE = 69;
`ifdef SOFTWARE_IS_QUARTUS
endpackage
`endif
`endif