// altddio_input_3bit.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module altddio_input_3bit (
		input  wire       ck,     //     ck.export
		output wire [7:0] dout,   //   dout.export
		input  wire [3:0] pad_in  // pad_in.export
	);

	altddio_input_3bit_altera_gpio_181_ejew3yq gpio_0 (
		.ck     (ck),     //     ck.export
		.dout   (dout),   //   dout.export
		.pad_in (pad_in)  // pad_in.export
	);

endmodule
