// convert_floating_to_16bit_fixed.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module convert_floating_to_16bit_fixed (
		input  wire [31:0] a,      //      a.a
		input  wire        areset, // areset.reset
		input  wire        clk,    //    clk.clk
		output wire [15:0] q       //      q.q
	);

	convert_floating_to_16bit_fixed_altera_fp_functions_181_iicpk4a fp_functions_0 (
		.clk    (clk),    //    clk.clk
		.areset (areset), // areset.reset
		.a      (a),      //      a.a
		.q      (q)       //      q.q
	);

endmodule
