// spiral_fft_4096_unscaled_stream_32bit.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module spiral_fft_4096_unscaled_stream_32bit (
		input  wire        clk_clk,             //        clk.clk
		input  wire        fft_reset_reset,     //  fft_reset.reset
		input  wire        spiral_fft_next,     // spiral_fft.next
		output wire        spiral_fft_next_out, //           .next_out
		input  wire [31:0] spiral_fft_x0,       //           .x0
		output wire [31:0] spiral_fft_y0,       //           .y0
		input  wire [31:0] spiral_fft_x1,       //           .x1
		output wire [31:0] spiral_fft_y1,       //           .y1
		input  wire [31:0] spiral_fft_x2,       //           .x2
		output wire [31:0] spiral_fft_y2,       //           .y2
		input  wire [31:0] spiral_fft_x3,       //           .x3
		output wire [31:0] spiral_fft_y3,       //           .y3
		input  wire [31:0] spiral_fft_x4,       //           .x4
		output wire [31:0] spiral_fft_y4,       //           .y4
		input  wire [31:0] spiral_fft_x5,       //           .x5
		output wire [31:0] spiral_fft_y5,       //           .y5
		input  wire [31:0] spiral_fft_x6,       //           .x6
		output wire [31:0] spiral_fft_y6,       //           .y6
		input  wire [31:0] spiral_fft_x7,       //           .x7
		output wire [31:0] spiral_fft_y7        //           .y7
	);

	dft_4096_fixed_32_bit_unscaled_stream_d spiral_fft_4096_unscaled_streaming_32bit (
		.clk      (clk_clk),             //       clock.clk
		.reset    (fft_reset_reset),     //       reset.reset
		.next     (spiral_fft_next),     // conduit_end.next
		.next_out (spiral_fft_next_out), //            .next_out
		.X0       (spiral_fft_x0),       //            .x0
		.Y0       (spiral_fft_y0),       //            .y0
		.X1       (spiral_fft_x1),       //            .x1
		.Y1       (spiral_fft_y1),       //            .y1
		.X2       (spiral_fft_x2),       //            .x2
		.Y2       (spiral_fft_y2),       //            .y2
		.X3       (spiral_fft_x3),       //            .x3
		.Y3       (spiral_fft_y3),       //            .y3
		.X4       (spiral_fft_x4),       //            .x4
		.Y4       (spiral_fft_y4),       //            .y4
		.X5       (spiral_fft_x5),       //            .x5
		.Y5       (spiral_fft_y5),       //            .y5
		.X6       (spiral_fft_x6),       //            .x6
		.Y6       (spiral_fft_y6),       //            .y6
		.X7       (spiral_fft_x7),       //            .x7
		.Y7       (spiral_fft_y7)        //            .y7
	);

endmodule
