config opencores_spi_standalone_altera_avalon_st_adapter_181_awjdnay_cfg;
		design opencores_spi_standalone_altera_avalon_st_adapter_181_awjdnay;
		instance opencores_spi_standalone_altera_avalon_st_adapter_181_awjdnay.error_adapter_0 use opencores_spi_standalone_error_adapter_181.opencores_spi_standalone_error_adapter_181_6bjmpii;
endconfig

