config altddio_input_5bit_altera_gpio_181_jjgtasy_cfg;
		design altddio_input_5bit_altera_gpio_181_jjgtasy;
		instance altddio_input_5bit_altera_gpio_181_jjgtasy.core use altddio_input_5bit_altera_gpio_core20_181.altera_gpio;
endconfig

