
#ifndef __GET_MAIN_PROCESSOR_RESET_ADDRESS_H
#define __GET_MAIN_PROCESSOR_RESET_ADDRESS_H

unsigned long get_main_processor_reset_address();
unsigned long get_main_processor_absolute_reset_address_in_main_processor_address_space();
unsigned long get_main_processor_ddr_base_in_main_processor_address_space();
#endif
