
//order of include here is important
#include "bootloader_config_of_dut_reset_addr.h"

unsigned long get_dut_processor_reset_address() {
	return	(BOOTLOADER_DUT_PROCESSOR_RESET_ADDRESS_NAME_IN_MAIN_PROCESSOR_SYSTEM_H - BOOTLOADER_DUT_PROCESSOR_DDR_SPACE_BASE_ADDRESS_IN_MAIN_PROCESSOR_SYSTEM_H);
}
unsigned long get_dut_processor_absolute_reset_address_in_main_processor_address_space() {
	return	(BOOTLOADER_DUT_PROCESSOR_RESET_ADDRESS_NAME_IN_MAIN_PROCESSOR_SYSTEM_H);
}

unsigned long get_dut_processor_ddr_base_in_main_processor_address_space() {
	return	BOOTLOADER_DUT_PROCESSOR_DDR_SPACE_BASE_ADDRESS_IN_MAIN_PROCESSOR_SYSTEM_H;
}

