config altddio_input_1bit_altera_gpio_181_nysxhoa_cfg;
		design altddio_input_1bit_altera_gpio_181_nysxhoa;
		instance altddio_input_1bit_altera_gpio_181_nysxhoa.core use altddio_input_1bit_altera_gpio_core20_181.altera_gpio;
endconfig

