config altddio_input_1bit_altera_gpio_181_pmulvoy_cfg;
		design altddio_input_1bit_altera_gpio_181_pmulvoy;
		instance altddio_input_1bit_altera_gpio_181_pmulvoy.core use altddio_input_1bit_altera_gpio_core20_181.altera_gpio;
endconfig

