config opencores_spi_standalone_cfg;
		design opencores_spi_standalone;
		instance opencores_spi_standalone.opencores_spi use opencores_spi_standalone_opencores_spi_10.opencores_spi_top;
		instance opencores_spi_standalone.opencores_spi_aux_control_in use opencores_spi_standalone_altera_avalon_pio_181.opencores_spi_standalone_altera_avalon_pio_181_wnfkwui;
		instance opencores_spi_standalone.opencores_spi_aux_control_out use opencores_spi_standalone_altera_avalon_pio_181.opencores_spi_standalone_altera_avalon_pio_181_4esfkty;
		instance opencores_spi_standalone.opencores_spi_currently_active use opencores_spi_standalone_altera_avalon_pio_181.opencores_spi_standalone_altera_avalon_pio_181_sn3rwoy;
		instance opencores_spi_standalone.opencores_spi_debug_tag_word use opencores_spi_standalone_altera_avalon_pio_181.opencores_spi_standalone_altera_avalon_pio_181_kaakf6y;
		instance opencores_spi_standalone.opencores_spi_manual_reset use opencores_spi_standalone_altera_avalon_pio_181.opencores_spi_standalone_altera_avalon_pio_181_ogj6yyi;
		instance opencores_spi_standalone.opencores_spi_sdio_helper use opencores_spi_standalone_altera_avalon_pio_181.opencores_spi_standalone_altera_avalon_pio_181_ogj6yyi;
		instance opencores_spi_standalone.simple_master_connection_without_burst_0 use opencores_spi_standalone_simple_master_connection_without_burst_10.simple_master_connection_without_burst;
		instance opencores_spi_standalone.mm_interconnect_0 use opencores_spi_standalone_altera_mm_interconnect_181.opencores_spi_standalone_altera_mm_interconnect_181_tt5wkpa;
		instance opencores_spi_standalone.rst_controller use opencores_spi_standalone_altera_reset_controller_181.altera_reset_controller;
endconfig

